// Generated by gencpp from file gym_gazebo/StepRequest.msg
// DO NOT EDIT!


#ifndef GYM_GAZEBO_MESSAGE_STEPREQUEST_H
#define GYM_GAZEBO_MESSAGE_STEPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace gym_gazebo
{
template <class ContainerAllocator>
struct StepRequest_
{
  typedef StepRequest_<ContainerAllocator> Type;

  StepRequest_()
    : seconds(0.0)
    , command()  {
    }
  StepRequest_(const ContainerAllocator& _alloc)
    : seconds(0.0)
    , command(_alloc)  {
  (void)_alloc;
    }



   typedef double _seconds_type;
  _seconds_type seconds;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::gym_gazebo::StepRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gym_gazebo::StepRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StepRequest_

typedef ::gym_gazebo::StepRequest_<std::allocator<void> > StepRequest;

typedef boost::shared_ptr< ::gym_gazebo::StepRequest > StepRequestPtr;
typedef boost::shared_ptr< ::gym_gazebo::StepRequest const> StepRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gym_gazebo::StepRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gym_gazebo::StepRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gym_gazebo::StepRequest_<ContainerAllocator1> & lhs, const ::gym_gazebo::StepRequest_<ContainerAllocator2> & rhs)
{
  return lhs.seconds == rhs.seconds &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gym_gazebo::StepRequest_<ContainerAllocator1> & lhs, const ::gym_gazebo::StepRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gym_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gym_gazebo::StepRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gym_gazebo::StepRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gym_gazebo::StepRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gym_gazebo::StepRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gym_gazebo::StepRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gym_gazebo::StepRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gym_gazebo::StepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aadc2f96f453613fb246fa09fd3c2ada";
  }

  static const char* value(const ::gym_gazebo::StepRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaadc2f96f453613fULL;
  static const uint64_t static_value2 = 0xb246fa09fd3c2adaULL;
};

template<class ContainerAllocator>
struct DataType< ::gym_gazebo::StepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gym_gazebo/StepRequest";
  }

  static const char* value(const ::gym_gazebo::StepRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gym_gazebo::StepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 seconds # simulation time\n"
"geometry_msgs/Twist command # action\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::gym_gazebo::StepRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gym_gazebo::StepRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seconds);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gym_gazebo::StepRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gym_gazebo::StepRequest_<ContainerAllocator>& v)
  {
    s << indent << "seconds: ";
    Printer<double>::stream(s, indent + "  ", v.seconds);
    s << indent << "command: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GYM_GAZEBO_MESSAGE_STEPREQUEST_H
